// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsmvfmymdkyrggmhdltb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzbXZmbXltZGt5cmdnbWhkbHRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMTkxNjMsImV4cCI6MjA2MDU5NTE2M30.Dsx_BiUR5HtbhQpIVNsdBjzk19f5MXMIionlkDjfC2E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);